#!/bin/bash

# Install Nginx (if not already installed)
sudo apt-get update
sudo apt-get -y install nginx

# Create a custom Nginx configuration file for the redirection
echo 'server {
    listen 80;
    server_name dumasphesihle.tech; # Replace with your domain name or server IP

    location /redirect_me {
        return 301 http://github.com;
    }

    location / {
        # Your regular Nginx configuration for other pages
    }
}' | sudo tee /etc/nginx/sites-available/redirect

# Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Test the Nginx configuration
sudo nginx -t

# Reload Nginx to apply the changes
sudo service nginx reload
