#!usr/bin/env bash

# Install Nginx (if not already installed)
sudo apt-get update
sudo apt-get -y install nginx

# Create a custom Nginx configuration file for the redirection
echo "Hello World!" > sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com permanent;/" /etc/nginx/sites-available/default
sudo service nginx start
