#!/usr/bin/bash
#Bash script that displays 10 times
#but for the 9th iteration displays hi
#on a newline
i=0
while [ $i -le 9 ]
do
    if [ $i -eq 8 ]
    then
       echo "Best School"
       echo "Hi"
    else
        echo "Best School"
    fi
    i=$(( $i + 1 ))
done
