#!/usr/bin/bash
#Bash script that displays 10 times
#but for the 9th iteration displays hi
#on a newline
i=1
while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
       echo "Hi"
    fi
    ((i + 1))
done
