#!/usr/bin/bash
#Bash script that displays 10 times
#but for the 9th iteration displays hi
#on a newline
i=1
while [ $i -le 10 ]
do
    if [ $i -eq 9 ]
    then
	echo "Best School"
        echo "Hi"
    else
	echo "Best School"
    fi
    i=$((i + 1))
done
